#
# Please note not all available settings / options are set here.
# For a full list, see the wiki
#

# Set programs that you use
$menu = wofi --conf ~/.config/wofi/config/config --style ~/.config/wofi/src/mocha/style.css
$browser = flatpak run io.gitlab.librewolf-community
$fileManager = pcmanfm
$terminal = kitty

source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/system.conf
source = ~/.config/hypr/looks.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/binds.conf
source = ~/.config/hypr/autostart.conf
