hl.on("hyprland.start", function()
	hl.exec_cmd("bash ~/.config/hypr/scripts/sleep.sh")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("bash ~/.config/hypr/scripts/wallpaper.sh")
	hl.exec_cmd("dunst")
	hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
	hl.exec_cmd("waybar")
	hl.exec_cmd("playerctld daemon")
end)
