# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
#windowrulev2 = immediate, fullscreen:1
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule = match:class *, suppress_event maximize # You'll probably like this.

# TEARING 
#windowrulev2 = immediate, class:^(Minecraft*)$

# AUTO-LOCK
windowrule = match:initial_title ^(Mozilla Firefox)$, idle_inhibit fullscreen
windowrule = match:class ^(io.github.celluloid_player.Celluloid)$, idle_inhibit fullscreen
#windowrulev2 = idleinhibit focus, initialTitle:^(Spotify Free)$
windowrule = match:class ^(WebCord)$, idle_inhibit fullscreen

# AUTO-FLOAT
windowrule = match:title ^(iwgtk)$, float on
windowrule = match:class ^(pavucontrol)$, float on
windowrule = match:class ^(nwg-look)$, float on
windowrule = match:title ^(Tor Browser)$, float on

# BLUR
# Text based
windowrule = match:class ^(kitty)$, opacity 0.8 0.8
windowrule = match:class ^(jetbrains-pycharm-ce)$, opacity 0.9 0.9
windowrule = match:class ^(jetbrains-idea-ce)$, opacity 0.9 0.9
# Media
windowrule = match:initial_title ^(LibreWolf)$, opacity 0.9 0.9
windowrule = match:initial_title ^(Spotify Free)$, opacity 0.9 0.9
windowrule = match:class ^(Discord)$, opacity 0.9 0.9
windowrule = match:class ^(org.keepassxc.KeePassXC)$, opacity 0.9 0.9
# System
layerrule = blur on, match:namespace waybar
windowrule = match:title ^(iwgtk)$, opacity 0.9 0.9
windowrule = match:class ^(pavucontrol)$, opacity 0.9 0.9
windowrule = match:class ^(nwg-look)$, opacity 0.9 0.9
windowrule = match:class ^(thunar)$, opacity 0.9 0.9
windowrule = match:class ^(gedit)$, opacity 0.9 0.9
#windowrulev2 = opacity 0.9 0.9, class:^(io.github.celluloid_player.Celluloid)$
#windowrulev2 = opacity 0.9 0.9, class:^(org.gnome.Loupe)$
windowrule = match:title ^(Flatseal)$, opacity 0.9 0.9

# Enables tearing in games
#windowrule = immediate, fullscreen: 1 # fucks my pc

# Fixes JetBrains tooltips
windowrule = match:class ^jetbrains-(?!toolbox),match:title ^win\d+$, no_initial_focus on    # Prevents jetbrains menu to disrupt window focus

# Fixes screensharing under XWayland
windowrule = match:class ^(xwaylandvideobridge)$, opacity 0.0 override 0.0 override
windowrule = match:class ^(xwaylandvideobridge)$ noanim
windowrule = match:class ^(xwaylandvideobridge)$, no_initial_focus on 
windowrule = match:class ^(xwaylandvideobridge)$, max_size 1 1
windowrule= match:class ^(xwaylandvideobridge)$, no_blur on
